# Jekyll Configuration

#
# Site settings
#

title: Hive
description: > # this ">" means to ignore newlines until "baseurl:"
  Hive is a DPoS blockchain empowering social and financial apps with fee-less, 3 second transactions.
baseurl: "" # the subpath of your site, e.g. /blog
license: The MIT License
license_url: https://opensource.org/licenses/MIT

#
# Build settings
#
repository: shmoogleosukami/hiveblockchain.info
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

destination: build

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from #run after sitemap to not include redirects in sitemap.xml
  
#
# Front Matter Defaults
#

defaults:
  -
    scope:
      path: ""
    values:
      layout: layout

